import codechicken.diffpatch.util.PatchMode
import net.minecraftforge.gradle.patcher.tasks.GenerateBinPatches
import net.minecraftforge.gradle.patcher.tasks.GeneratePatches
import net.minecraftforge.gradle.patcher.tasks.ApplyPatches
import net.minecraftforge.gradle.mcp.tasks.GenerateSRG

plugins {
    java
    id("de.undercouch.download")
    id("net.minecraftforge.gradle")
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("wtf.gofancy.fancygradle")
}

evaluationDependsOn(":XU2-Base")
java.toolchain.languageVersion.set(JavaLanguageVersion.of(8))

val mappingsChannel:    String by project
val mappingsVersion:    String by project
val versionJEI:         String by project
val versionForge:       String by project

val patchedJar: File = buildDir.resolve("applyProjectPatches/output.jar")
val patchesDir: File = projectDir.resolve("patches")

val taskGroup:  String = "xu2 patcher ~ patched"
val XU2Base:    Project = project(":XU2-Base")
val baseSource: File = XU2Base.projectDir.resolve("src")
val src:        File = projectDir.resolve("src")
val libs:       File = buildDir.resolve("libs")

fancyGradle {
    patches {
        asm
        codeChickenLib
        coremods
        resources
        mergetool
    }
}

repositories {
    mavenCentral()
    maven {
        name = "Progwml6 maven"
        url = uri("https://dvs1.progwml6.com/files/maven/")
    }
}

minecraft {
    mappings(mappingsChannel, mappingsVersion)
}

dependencies {
    minecraft(group = "net.minecraftforge", name = "forge", version = "1.12.2-${versionForge}")
    compileOnly(group = "mezz.jei", name = "jei_1.12.2", version = versionJEI)
}

tasks {
    // Source related
    register<Copy>("Copy Source") {
        group = taskGroup
        if (!baseSource.resolve("build.gradle").exists()) dependsOn(XU2Base.tasks.getByName("Setup Base Source"))
        from(baseSource)
        filteringCharset = "UTF-8"
        into(src)
    }

    register<ApplyPatches>("Apply Project Patches") {
        group = taskGroup
        val baseSourceJar = XU2Base.tasks.getByName<Zip>("Source Jar ~ Full (Base)")
        dependsOn(baseSourceJar)

        base.set(baseSourceJar.archiveFile.get().asFile)
        patches.set(File(patchesDir, "project"))
        rejects.set(File(buildDir, "applyProjectPatches/rejects.zip"))
        output.set(patchedJar)
        patchMode.set(PatchMode.OFFSET)
        isPrintSummary = true

        doLast {
            // Fix corrupted assets (No idea why ApplyPatches breaks them :P)
            val tempDir = buildDir.resolve("tmp/asset-fix")
            tempDir.deleteRecursively()
            tempDir.mkdirs()

            copy {
                from(zipTree(patchedJar))
                into(tempDir)
            }

            copy {
                from(zipTree(base)) {
                    include("**/*.png", "**/*.obj", "**/*.ico", "**/*.bin")
                }
                into(tempDir)
                duplicatesStrategy = DuplicatesStrategy.INCLUDE
            }

            ant.withGroovyBuilder {
                "zip"("destfile" to patchedJar, "basedir" to tempDir)
            }

            tempDir.deleteRecursively()
        }
    }

    register<Copy>("Setup Patched Source") {
        group = taskGroup
        description =
            "Used to copy over the source project from XU2-Base, and apply patches generated by \"Apply Project Patches\""
        filteringCharset = "UTF-8"

        dependsOn("Apply Project Patches")
        if (!srcExists()) dependsOn("Copy Source")

        from(zipTree(patchedJar))
        into("src")
        doLast { execSourceTask("--refresh-dependencies") }
    }

    // Runs
    register("Run Client ~ 1.12") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Patched Source")
        dependsOn(rootProject.tasks.getByName("Api Jar ~ 1.12"))
        doLast { execSourceTask(":1.12:runClient") }
    }

    // Source Jar Generation
    register<Zip>("Source Jar ~ Full") {
        group = taskGroup
        description =
            "Used to package all versions of the mod into a single jar, for Patching the Patched Project. Should not be used to generate binary patches"
        if (!srcExists()) dependsOn("Setup Patched Source")
        archiveClassifier.set("sources")
        archiveBaseName.set("XU2-Project")
        from(src) {
            include("**")
            exclude("gradle")
            exclude("**/.idea")
            exclude("**/.gradle")
            exclude("**/build")
            exclude("**/run")
        }
    }

    // Those are here mostly for Patch generation tasks, as those are a bit faster than build task.
    // If full jar or deobf one is required, use build (as it also generates source jar)
    register("Source Jar ~ 1.12") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Patched Source")
        doFirst { packageSource("1.12") }
    }

    register("Source Jar ~ 1.11") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Patched Source")
        doFirst { packageSource("1.11") }
    }

    register("Source Jar ~ 1.10") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Patched Source")
        doFirst { packageSource("1.10.2") }
    }

    // Jar Generation
    register("Build ~ 1.12") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Patched Source")
        doFirst { buildSource("1.12") }
    }

    register("Build ~ 1.11") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Patched Source")
        doFirst { buildSource("1.11") }
    }

    register("Build ~ 1.10") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Patched Source")
        doFirst { buildSource("1.10.2") }
    }

    // Patches Generation
    register<GeneratePatches>("Generate Patches ~ Project") {
        group = taskGroup

        val baseSourceJar = XU2Base.tasks.getByName<Zip>("Source Jar ~ Full (Base)")
        val sourceJar = getByName<Zip>("Source Jar ~ Full")

        dependsOn(baseSourceJar)
        dependsOn(sourceJar)

        base.set(baseSourceJar.archiveFile.get().asFile)
        modified.set(sourceJar.archiveFile.get().asFile)
        output.set(File(patchesDir, "project"))
        isPrintSummary = true
    }

    register<GeneratePatches>("Generate Patches ~ 1.12") {
        group = taskGroup

        dependsOn(XU2Base.tasks.getByName("Source Jar ~ 1.12 (Base)"))
        dependsOn(getByName("Source Jar ~ 1.12"))

        base.set(XU2Base.buildDir.resolve("libs/1.12/ExtraUtils2-Sources.jar"))
        modified.set(libs.resolve("1.12/ExtraUtils2-Sources.jar"))
        output.set(patchesDir.resolve("1.12"))
        isPrintSummary = true
    }

    register<GenerateBinPatches>("Generate Binary Patches ~ 1.12") {
        group = taskGroup
        configureBinPatchTask(this, "1.12")
    }

    register("Cleanup ~ Patched") {
        group = taskGroup
        doFirst {
            execSourceTask("clean")
            execSourceTask("--stop")
        }
    }
}

fun configureBinPatchTask(task: GenerateBinPatches, version: String) {
    val createMcpToSrg = tasks.getByName<GenerateSRG>("createMcpToSrg")
    val baseJar = XU2Base.tasks.getByName("Build ~ $version (Base)")
    val patchedJar = project.tasks.getByName("Build ~ $version")
    task.dependsOn(createMcpToSrg)
    task.dependsOn(baseJar)
    task.dependsOn(patchedJar)
    task.patchSets.setFrom(patchesDir.resolve(version))
    task.cleanJar.set(XU2Base.buildDir.resolve("libs/$version/ExtraUtils2.jar"))
    task.dirtyJar.set(project.buildDir.resolve("libs/$version/ExtraUtils2.jar"))
    task.output.set(rootDir.resolve("src/main/generated/patches/1.12/patches.pack.lzma"))
    task.srg.set(createMcpToSrg.output)
    task.args.set(listOf(
            "--output", "{output}",
            "--patches", "{patches}",
            "--srg", "{srg}",
            "--clean", "{clean}",
            "--create", "{dirty}",
            "--prefix", "binpatch/merged"
    ))
}

//TODO: Rework build/package sources. We can just name files with version suffix????
fun buildSource(ver: String) {
    val libs = src.resolve("$ver/build/libs")
    val final = buildDir.resolve("libs/$ver")
    execSourceTask(":$ver:build")

    // If version changed, it is possible that additional jars will be created.
    // If that happens, Delete and build again to not break other tasks.
    if (libs.list().size > 3) {
        libs.deleteRecursively()
        buildSource(ver)
        return;
    }

    final.mkdirs()
    libs.listFiles()?.forEach {
        val name: String = if (it.name.endsWith("-deobf.jar")) {
            "ExtraUtils2-Deobf.jar"
        } else if (it.name.endsWith("-sources.jar")) {
            "ExtraUtils2-Sources.jar"
        } else {
            "ExtraUtils2.jar"
        }
        it.copyTo(File(final, name), overwrite = true)
    }
}

fun packageSource(ver: String) {
    val libs = src.resolve("$ver/build/libs")
    val final = buildDir.resolve("libs/$ver")
    execSourceTask(":$ver:sourceJar")

    final.mkdirs()
    var sourcesCopied = false
    var duplicate = false
    libs.listFiles()?.forEach {
        if (it.name.endsWith("sources.jar")) {
            if (sourcesCopied) duplicate = true;
            it.copyTo(File(final,"ExtraUtils2-Sources.jar"), overwrite = true)
            sourcesCopied = true;
        }
    }
    if (duplicate) {
        libs.deleteRecursively()
        packageSource(ver)
    }
}

/**
 * Used to execute tasks with use of the Gradle Wrapper from the XU2 Project.
 * Note: Yes I know this is cursed, Yes I tried a lot of stuff to make this work.
 */
fun execSourceTask(task: String) {
    val os = System.getProperty("os.name").toLowerCase()
    val javaHome = System.getProperty("java.home")

    if (!srcExists()) {
        println("Skipping execution of \"$task\" on the XU2 Source, as it doesn't exist!")
        return
    }

    println("Using Java at: $javaHome to execute task \"$task\" on the XU2 Source...")


    val pb = if (os.contains("win")) {
        ProcessBuilder(File(projectDir,"../gradle-3.0-wrapper/gradlew.bat").absolutePath, task)
    } else {
        //TODO: Test if this works on SH / Linux
        ProcessBuilder(File(projectDir,"../gradle-3.0-wrapper/gradlew").absolutePath, task)
    }

    // Doesn't work in IDE :V Still requires manual reading of the output streams.
//    pb.inheritIO()
    pb.directory(src)
    pb.environment()["JAVA_HOME"] = javaHome;

    val process = pb.start();
    val reader = process.inputStream.bufferedReader()
    val errorReader = process.errorStream.bufferedReader()

    Thread { reader.lines().forEach { println(it) } }.start()
    Thread { errorReader.lines().forEach { logger.error(it) } }.start()

    process.waitFor()

    val exitCode = process.exitValue();

    println("Process ended with exit code: $exitCode")

    if (exitCode != 0) throw IllegalStateException("Exit code different than 0! Something went wrong.")
}

fun srcExists(): Boolean {
    return File(src, "build.gradle").exists();
}

// Only here so source code is possible to edit from the main project view. For better compatibility, open the Source project separately.
subprojects {
    if (project.name in listOf("1.10.2", "1.11", "1.12")) {
        apply(plugin = "java-library")
        apply(plugin = "idea")

        var forgeVer = "unknown"

        repositories {
            maven { url = uri("https://maven.thiakil.com") }
            maven { url = uri("https://dvs1.progwml6.com/files/maven") }
            maven { url = uri("https://maven.blamejared.com") }
        }

        // Why SWITCH is called WHEN in Kotlin ughr.
        when (project.name) {
            "1.10.2" -> {
                forgeVer = "1.10.2"
                dependencies {
                    compileOnly(group = "mezz.jei", name = "jei_1.10.2", version = "3.13.3.380")
                    compileOnly(group = "slimeknights.mantle", name = "Mantle", version = "1.10.2-1.1.3.199")
                    compileOnly(group = "slimeknights", name = "TConstruct", version = "1.10.2-2.6.1.464")
                    compileOnly(rootProject)
                }

                sourceSets {
                    main {
                        java {
                            srcDir("src/main/java")
                            srcDir("src/compat/java")
                            srcDir("src/compat111/java")
                            srcDir("src/api/java")
                        }
                        resources {
                            srcDir("src/main/resources")
                            srcDir("src/compat/resources")
                        }
                    }
                }
            }

            "1.11" -> {
                forgeVer = "1.11.2"
                dependencies {
                    compileOnly(group = "mezz.jei", name = "jei_1.11", version = "4.1.1.208")
                    parent?.let { compileOnly(it.project("1.10.2")) }
                    compileOnly(rootProject)
                }
                sourceSets { main { java { srcDir("src/main/java") } } }
            }

            "1.12" -> {
                forgeVer = "1.12.2"
                dependencies {
                    compileOnly(group = "CraftTweaker2", name = "CraftTweaker2-API", version = "4.1.9.6")
                    compileOnly(group = "mezz.jei", name = "jei_1.12.2", version = "4.12.1.217")
                    compileOnly(group = "slimeknights.mantle", name = "Mantle", version = "1.12-1.3.1.22")
                    compileOnly(group = "slimeknights", name = "TConstruct", version = "1.12-2.7.2.508")
                    compileOnly(group = "com.azanor.baubles", name = "Baubles", version = "1.12-1.5.2")
                    compileOnly(rootProject)
                    parent?.let { compileOnly(it.project("1.10.2")) }
                }
                sourceSets { main { java { srcDir("src/main/java") } } }
            }
        }


        val libs = projectDir.resolve("../../../libs");
        val forge = libs.resolve("Forge-${forgeVer}.jar")
        val jars = libs.resolve(forgeVer)
        dependencies {
            if (jars.exists() && jars.listFiles()?.isNotEmpty() == true) {
                implementation(fileTree(jars) { include("*.jar") })
            } else {
                logger.warn("!! Missing libraries for minecraft $forgeVer! | Did you execute \"Setup Base Source\"?")
            }

            if (forge.exists()) {
                implementation(files(forge))
            } else {
                logger.warn("!! Forge JAR missing for XU2:${project.name} at: ${forge.absolutePath} | Did you execute \"Setup Base Source\"?")
            }
        }
    }
}