import codechicken.diffpatch.util.PatchMode
import de.undercouch.gradle.tasks.download.Download
import groovy.json.JsonSlurper
import net.minecraftforge.gradle.patcher.tasks.ApplyPatches
import net.minecraftforge.gradle.patcher.tasks.GeneratePatches
import org.gradle.kotlin.dsl.register
import java.io.FileNotFoundException

plugins {
    java
    idea
    id("de.undercouch.download")
    id("com.github.johnrengelman.shadow") version "6.1.0"
}

java.toolchain.languageVersion.set(JavaLanguageVersion.of(8))

val taskGroup:          String = "xu2 patcher ~ base"
val XU2SourceURL:       String by project
val src:                File = projectDir.resolve("src")
val patchesDir:         File = projectDir.resolve("patches")

tasks {
    // Download and setup the source.
    register<Download>("Download Source") {
        group = taskGroup
        inputs.property("sourceUrl", XU2SourceURL)
        src(XU2SourceURL)
        dest(buildDir.resolve("sources/XU2-Sources.zip"))
        overwrite(false)
    }

    register<Zip>("Flatten Source") {
        group = taskGroup
        val sourceJar = getByName<Download>("Download Source")
        dependsOn(sourceJar)

        archiveFileName.set("XU2-Processed.zip")
        destinationDirectory.set(buildDir.resolve("sources"))

        val xu2RepoName = XU2SourceURL
            .removePrefix("https://github.com/rwtema/")
            .replace("/archive/", "-")
            .removeSuffix(".zip")

        from(zipTree(sourceJar.dest).matching {
            include("$xu2RepoName/**")
        }) {
            eachFile {
                path = path.removePrefix("$xu2RepoName/")
            }
            includeEmptyDirs = false
        }
    }

    // Setup Patches Generation
    register<GeneratePatches>("Generate Patches") {
        group = taskGroup

        val baseSourceJar = getByName<Zip>("Flatten Source")
        val sourceJar = getByName<Zip>("Source Jar ~ Full (Base)")

        dependsOn(baseSourceJar)
        dependsOn(sourceJar)

        base.set(baseSourceJar.archiveFile.get().asFile)
        modified.set(sourceJar.archiveFile.get().asFile)
        output.set(patchesDir)
        isPrintSummary = true
    }

    register<ApplyPatches>("Patch Source") {
        group = taskGroup
        val baseSourceJar = getByName<Zip>("Flatten Source")
        dependsOn(baseSourceJar)

        val out = buildDir.resolve("sources/XU2-Patched.zip")
        base.set(baseSourceJar.archiveFile.get().asFile)
        patches.set(patchesDir)
        rejects.set(buildDir.resolve("sources/Rejected-Patches.zip"))
        output.set(out)
        patchMode.set(PatchMode.OFFSET)
        isPrintSummary = true

        doLast {
            // Fix corrupted assets (No idea why ApplyPatches breaks them :P)
            val tempDir = buildDir.resolve("tmp/asset-fix")
            tempDir.deleteRecursively()
            tempDir.mkdirs()

            copy {
                from(zipTree(out))
                into(tempDir)
            }

            copy {
                from(zipTree(base)) {
                    include("**/*.png", "**/*.obj", "**/*.ico", "**/*.bin")
                }
                into(tempDir)
                duplicatesStrategy = DuplicatesStrategy.INCLUDE
            }

            ant.withGroovyBuilder {
                "zip"("destfile" to out, "basedir" to tempDir)
            }

            tempDir.deleteRecursively()
        }
    }

    register<Copy>("Setup Base Source") {
        group = taskGroup;
        val patchedSource = getByName<ApplyPatches>("Patch Source")
        val libs = projectDir.resolve("../libs")
        dependsOn(patchedSource)
        outputs.dir(libs)
        outputs.dir(src)

        outputs.upToDateWhen {
            libs.exists() && src.exists() && libs.listFiles()?.isNotEmpty() ?: false
        }

        from(zipTree(patchedSource.output))
        into(src)

        doLast {
            // Using own Gradle 3.0 wrapper to make everything work, as XU2 project is cursed in structure,
            // use execSourceTask func for command execution on the source code.
            //TODO: Figure out why FG 2.3 fails to apply certain ATs when running setupDecompWorkspace
            // For now we are going to use jars generated by build task, and continue the dev w/o sources.
            // Oh well!
            execSourceTask("--refresh-dependencies")
            execSourceTask(":1.10.2:build")
            execSourceTask(":1.11:build")
            execSourceTask(":1.12:build")
//            execSourceTask(":1.10.2:setupDecompWorkspace")
//            execSourceTask(":1.11:setupDecompWorkspace")
//            execSourceTask(":1.12:setupDecompWorkspace")

            // Strips new lines at the end of the source files, as those cause random patches to generate in the patched project.
            // This will generate a lot of patches in the base, but we don't really care!
            fileTree(src) {
                include("**/*.java")
                forEach { file ->
                    val content = file.readText(Charsets.UTF_8)
                    if (content.endsWith("\n")) file.writeText(content.removeSuffix("\n"))
                }
            }

            // Removes random test file that for some reason is included in the source jar
            src.resolve("1.10.2/src/main/resources/assets/test").delete()

            // Get the Minecraft/Forge Jars to the libs.
            // FG5 does not support anything older than the latest versions of MC 1.12.2,
            // requiring the wrapper project to use jars generated and downloaded by the old FG2 setup of XU2.
            // This is the most elegant solution for full IDE support in the project without having to run the original project in the IDE.
            if (libs.exists()) libs.deleteRecursively()
//            src.resolve("1.10.2/.gradle/minecraft/forgeSrc-1.10.2-12.18.3.2511-PROJECT(1.10.2).jar")
//                .copyTo(libs.resolve("Forge-1.10.2.jar"))
//            src.resolve("1.10.2/.gradle/minecraft/forgeSrc-1.10.2-12.18.3.2511-PROJECT(1.10.2)-sources.jar")
//                .copyTo(libs.resolve("Forge-1.10.2-Sources.jar"))
//            src.resolve("1.11/.gradle/minecraft/forgeSrc-1.11.2-13.20.1.2588-PROJECT(1.11).jar")
//                .copyTo(libs.resolve("Forge-1.11.2.jar"))
//            src.resolve("1.11/.gradle/minecraft/forgeSrc-1.11.2-13.20.1.2588-PROJECT(1.11)-sources.jar")
//                .copyTo(libs.resolve("Forge-1.11.2-Sources.jar"))
//            src.resolve("1.12/.gradle/minecraft/forgeSrc-1.12.2-14.23.5.2769-PROJECT(1.12).jar")
//                .copyTo(libs.resolve("Forge-1.12.2.jar"))
//            src.resolve("1.12/.gradle/minecraft/forgeSrc-1.12.2-14.23.5.2769-PROJECT(1.12)-sources.jar")
//                .copyTo(libs.resolve("Forge-1.12.2-Sources.jar"))
            src.resolve("1.10.2/.gradle/minecraft/forgeBin-1.10.2-12.18.3.2511-PROJECT(1.10.2).jar")
                .copyTo(libs.resolve("Forge-1.10.2.jar"))
            src.resolve("1.11/.gradle/minecraft/forgeBin-1.11.2-13.20.1.2588-PROJECT(1.11).jar")
                .copyTo(libs.resolve("Forge-1.11.2.jar"))
            src.resolve("1.12/.gradle/minecraft/forgeBin-1.12.2-14.23.5.2769-PROJECT(1.12).jar")
                .copyTo(libs.resolve("Forge-1.12.2.jar"))

            // Get the libraries jars to the libs.
            // Copying them to the project because gradle caches can be cleared or invalidated.
            // We just can't be sure lol.
            val osProp = System.getProperty("os.name").toLowerCase();
            val os = when {
                osProp.contains("win") -> "windows"
                osProp.contains("mac") -> "osx"
                else -> "linux"
            }
            val gradleCache = File(System.getProperty("user.home")).resolve(".gradle/caches")
            println("Gradle caches for os: \"$os\" located at: \"$gradleCache\"");

            for (mc in listOf("1.10.2", "1.11.2", "1.12.2")) copyLibs(libs, gradleCache, mc, os)
        }
    }

    register<Copy>("Add Gradle to Source") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Base Source")
        from (projectDir.resolve("../gradle-3.0-wrapper"))
        into(src)
    }

    // Jar Generation
    register("Build ~ 1.12 (Base)") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Base Source")
        doFirst { buildSource("1.12") }
    }

    register("Build ~ 1.11 (Base)") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Base Source")
        doFirst { buildSource("1.11") }
    }

    register("Build ~ 1.10 (Base)") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Base Source")
        doFirst { buildSource("1.10.2") }
    }

    // Source Jar Generation
    register<Zip>("Source Jar ~ Full (Base)") {
        group = taskGroup
        description = "Used to package all versions of the mod into a single jar, for Patching the Patched Project. Should not be used to generate binary patches"
        if (!srcExists()) dependsOn("Setup Base Source")
        archiveClassifier.set("sources")
        from(src) {
            include("**")
            exclude("gradle")
            exclude("**/.idea")
            exclude("**/.gradle")
            exclude("**/build")
            exclude("**/run")
        }
    }

    // Those are here mostly for Patch generation tasks, as those are a bit faster than build task.
    // If full jar or deobf one is required, use build (as it also generates source jar)
    register("Source Jar ~ 1.12 (Base)") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Source")
        doFirst { packageSource("1.12") }
    }

    register("Source Jar ~ 1.11 (Base)") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Source")
        doFirst { packageSource("1.11") }
    }

    register("Source Jar ~ 1.10 (Base)") {
        group = taskGroup
        if (!srcExists()) dependsOn("Setup Source")
        doFirst { packageSource("1.10.2") }
    }

    register("Cleanup ~ Base") {
        group = taskGroup
        doFirst {
            execSourceTask("clean")
            execSourceTask("--stop")
        }
    }
}

fun copyLibs(libs: File, gradleCache: File, ver: String, devOS: String) {
    val manifestFile = libs.resolve("$ver.json")
    val jarsCache = gradleCache.resolve("modules-2/files-2.1")

    gradleCache.resolve("minecraft/versionJsons/$ver.json").copyTo(manifestFile)

    ((JsonSlurper().parse(manifestFile) as Map<*, *>)["libraries"] as List<Map<*, *>>).forEach { lib ->
        val data = (lib["name"] as String).split(":")
        var jar = jarsCache.resolve("${data[0]}/${data[1]}/${data[2]}").walkTopDown().find { it.extension == "jar" && it.name.equals("${data[1]}-${data[2]}.jar") }

        if (jar == null) {
            // Jar not found, check if lib is allowed.
            if (lib["rules"] != null) {
                val rules = lib["rules"] as List<Map<*,*>>
                for (rule in rules) {
                    if (rule["os"] == null) continue
                    val os = rule["os"] as Map<*,*>
                    if (os.isEmpty()) continue
                    when (rule["action"]) {
                        "allow" -> {
                            if (os["name"] != devOS) {
                                logger.warn("Skipping library: ${lib["name"]} for version: $ver because it's not allowed on your operating system.")
                                return@forEach
                            }
                        }
                        "disallow" -> {
                            if (os["name"] == devOS) {
                                logger.warn("Skipping library: ${lib["name"]} for version: $ver because it's not allowed on your operating system.")
                                return@forEach
                            }
                        }
                    }
                }
            }

            // If lib allowed, check for natives.
            if (lib["natives"] != null) {
                val natives = lib["natives"] as Map<*,*>
                if (natives[devOS] != null)
                    jar = jarsCache.resolve("${data[0]}/${data[1]}/${data[2]}").walkTopDown().find { it.extension == "jar" && it.name.equals("${data[1]}-${data[2]}-${natives[devOS]}.jar")}
            }

            if (jar == null) throw FileNotFoundException("Can't find library: ${lib["name"]} in gradle caches for Minecraft $ver!")
            println("Using native version of library: ${lib["name"]} for os: $devOS")
        }
        val dst = libs.resolve("$ver/${data[1]}-${data[2]}.jar");
        if (dst.exists()) {
            logger.warn("Duplicate library: ${lib["name"]} for version: $ver")
            return@forEach
        }
        jar.copyTo(dst)
    }
    println("Copied libraries for Minecraft (Forge) $ver");
}
//TODO: Rework build/package sources. We can just name files with version suffix????
fun buildSource(ver: String) {
    val libs = src.resolve("$ver/build/libs")
    val final = buildDir.resolve("libs/$ver")
    execSourceTask(":$ver:build")

    // If version changed, it is possible that additional jars will be created.
    // If that happens, Delete and build again to not break other tasks.
    if (libs.list().size > 3) {
        libs.deleteRecursively()
        buildSource(ver)
        return;
    }

    final.mkdirs()
    libs.listFiles()?.forEach {
        val name: String = if (it.name.endsWith("-deobf.jar")) {
            "ExtraUtils2-Deobf.jar"
        } else if (it.name.endsWith("-sources.jar")) {
            "ExtraUtils2-Sources.jar"
        } else {
            "ExtraUtils2.jar"
        }
        it.copyTo(File(final, name), overwrite = true)
    }
}

fun packageSource(ver: String) {
    val libs = src.resolve("$ver/build/libs")
    val final = buildDir.resolve("libs/$ver")
    execSourceTask(":$ver:sourceJar")

    final.mkdirs()
    var sourcesCopied = false
    var duplicate = false
    libs.listFiles()?.forEach {
        if (it.name.endsWith("sources.jar")) {
            if (sourcesCopied) duplicate = true;
            it.copyTo(final.resolve("ExtraUtils2-Sources.jar"), overwrite = true)
            sourcesCopied = true;
        }
    }
    if (duplicate) {
        libs.deleteRecursively()
        packageSource(ver)
    }
}

repositories {
    mavenCentral()
    maven { 
        name = "Progwml6 maven"
        url = uri("https://dvs1.progwml6.com/files/maven/")
    }
}

/**
 * Used to execute tasks with use of the Gradle Wrapper from the XU2 Project.
 * Note: Yes I know this is cursed, Yes I tried a lot of stuff to make this work.
 */
fun execSourceTask(task: String) {
    val os = System.getProperty("os.name").toLowerCase()
    val javaHome = System.getProperty("java.home")

    if (!srcExists()) {
        println("Skipping execution of \"$task\" on the XU2 Source, as it doesn't exist!")
        return
    }

    println("Using Java at: $javaHome to execute task \"$task\" on the XU2 Source...")


    val pb = if (os.contains("win")) {
        ProcessBuilder(File(projectDir,"../gradle-3.0-wrapper/gradlew.bat").absolutePath, task)
    } else {
        //TODO: Test if this works on SH / Linux
        ProcessBuilder(File(projectDir,"../gradle-3.0-wrapper/gradlew").absolutePath, task)
    }

    // Doesn't work in IDE :V Still requires manual reading of the output streams.
//    pb.inheritIO()
    pb.directory(src)
    pb.environment()["JAVA_HOME"] = javaHome;

    val process = pb.start();
    val reader = process.inputStream.bufferedReader()
    val errorReader = process.errorStream.bufferedReader()

    Thread { reader.lines().forEach { println(it) } }.start()
    Thread { errorReader.lines().forEach { logger.error(it) } }.start()

    process.waitFor()

    val exitCode = process.exitValue();

    println("Process ended with exit code: $exitCode")

    if (exitCode != 0) throw IllegalStateException("Exit code different than 0! Something went wrong.")
}

fun srcExists(): Boolean {
    return File(src, "build.gradle").exists();
}

// Only here so source code is possible to edit from the main project view. For better compatibility, open the Source project separately.
subprojects {
    if (project.name in listOf("1.10.2", "1.11", "1.12")) {
        apply(plugin = "java-library")
        apply(plugin = "idea")

        var forgeVer = "unknown"

        repositories {
            maven { url = uri("https://maven.thiakil.com") }
            maven { url = uri("https://dvs1.progwml6.com/files/maven") }
            maven { url = uri("https://maven.blamejared.com") }
        }

        // Why SWITCH is called WHEN in Kotlin ughr.
        when (project.name) {
            "1.10.2" -> {
                forgeVer = "1.10.2"
                dependencies {
                    compileOnly(group = "mezz.jei", name = "jei_1.10.2", version = "3.13.3.380")
                    compileOnly(group = "slimeknights.mantle", name = "Mantle", version = "1.10.2-1.1.3.199")
                    compileOnly(group = "slimeknights", name = "TConstruct", version = "1.10.2-2.6.1.464")
                }

                sourceSets {
                    main {
                        java {
                            srcDir("src/main/java")
                            srcDir("src/compat/java")
                            srcDir("src/compat111/java")
                            srcDir("src/api/java")
                        }
                        resources {
                            srcDir("src/main/resources")
                            srcDir("src/compat/resources")
                        }
                    }
                }
            }

            "1.11" -> {
                forgeVer = "1.11.2"
                dependencies {
                    compileOnly(group = "mezz.jei", name = "jei_1.11", version = "4.1.1.208")
                    parent?.let { compileOnly(it.project("1.10.2")) }
                }
                sourceSets { main { java { srcDir("src/main/java") } } }
            }

            "1.12" -> {
                forgeVer = "1.12.2"
                dependencies {
                    compileOnly(group = "CraftTweaker2", name = "CraftTweaker2-API", version = "4.1.9.6")
                    compileOnly(group = "mezz.jei", name = "jei_1.12.2", version = "4.12.1.217")
                    compileOnly(group = "slimeknights.mantle", name = "Mantle", version = "1.12-1.3.1.22")
                    compileOnly(group = "slimeknights", name = "TConstruct", version = "1.12-2.7.2.508")
                    compileOnly(group = "com.azanor.baubles", name = "Baubles", version = "1.12-1.5.2")
                    parent?.let { compileOnly(it.project("1.10.2")) }
                }
                sourceSets { main { java { srcDir("src/main/java") } } }
            }
        }


        val libs = projectDir.resolve("../../../libs");
        val forge = libs.resolve("Forge-${forgeVer}.jar")
        val jars = libs.resolve(forgeVer)
        dependencies {
            if (jars.exists() && jars.listFiles()?.isNotEmpty() == true) {
                implementation(fileTree(jars) { include("*.jar") })
            } else {
                logger.warn("!! Missing libraries for minecraft $forgeVer! | Did you execute \"Setup Base Source\"?")
            }

            if (forge.exists()) {
                implementation(files(forge))
            } else {
                logger.warn("!! Forge JAR missing for XU2:${project.name} at: ${forge.absolutePath} | Did you execute \"Setup Base Source\"?")
            }
        }
    }
}